<?php

namespace Tests\Feature;

use App\Models\AuditLog;
use App\Models\Atk;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class AuditLogTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        // Setup admin and staff
        $this->admin = User::factory()->create(['role' => 'admin']);
        $this->staff = User::factory()->create(['role' => 'staff']);
    }

    public function test_admin_can_access_audit_trail()
    {
        $response = $this->actingAs($this->admin)->get(route('audit-logs.index'));
        $response->assertStatus(200);
    }

    public function test_staff_cannot_access_audit_trail()
    {
        $response = $this->actingAs($this->staff)->get(route('audit-logs.index'));
        $response->assertStatus(403);
    }

    public function test_create_action_generates_audit_log()
    {
        $this->actingAs($this->admin);

        $response = $this->postJson(route('atk.store'), [
            'kode_atk' => 'ATK001',
            'nama_atk' => 'Kertas A4',
            'jenis_atk' => 'Kertas',
            'satuan' => 'Rim',
            'keterangan' => 'Test',
            'jumlah' => 10,
            'harga' => 50000,
            'status' => 'Aktif',
        ]);

        $response->assertStatus(200);

        $this->assertDatabaseHas('audit_logs', [
            'action' => 'CREATE',
            'module' => 'Atk',
            'user_id' => $this->admin->id,
        ]);
    }

    public function test_update_action_generates_audit_with_old_and_new_values()
    {
        $this->actingAs($this->admin);
        
        $atk = Atk::create([
            'kode_atk' => 'ATK002',
            'nama_atk' => 'Pena',
            'jenis_atk' => 'Tulis',
            'satuan' => 'Pcs',
            'status' => 'Aktif',
            'jumlah' => 10,
            'harga' => 50000,
        ]);

        // clear previous log generated by create
        AuditLog::truncate();

        $response = $this->putJson(route('atk.update', $atk->id), [
            'kode_atk' => 'ATK002',
            'nama_atk' => 'Pena Merah',
            'jenis_atk' => 'Tulis',
            'satuan' => 'Pcs',
            'status' => 'Aktif',
            'jumlah' => 10,
            'harga' => 50000,
        ]);

        $response->assertStatus(200);

        $log = AuditLog::where('action', 'UPDATE')->first();
        $this->assertNotNull($log);
        $this->assertStringContainsString('Pena Merah', $log->new_values);
        $this->assertStringContainsString('Pena', $log->old_values);
    }

    public function test_sensitive_fields_are_hidden_in_auth_logs()
    {
        $user = User::factory()->create([
            'email' => 'testlog@example.com',
            'password' => bcrypt('password123'),
        ]);

        $response = $this->postJson(route('login.post'), [
            'email' => 'testlog@example.com',
            'password' => 'password123',
        ]);

        $log = AuditLog::where('action', 'LOGIN')->first();
        $this->assertNotNull($log);
        
        // Assert that the raw password is NOT in the new_values/old_values if we pass it
        // Since we pass the user model, let's check if the user model hides it.
        $this->assertStringNotContainsString('password123', $log->new_values ?? '');
        $this->assertStringNotContainsString('password123', $log->old_values ?? '');
    }
}
